// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © frazilex

//@version=4
study(title="Moving Average Exponential", shorttitle="EMA", overlay=true, resolution="")
len = input(44, minval=1, title="Length")
src = input(close, title="Source")
offset = input(title="Offset", type=input.integer, defval=0, minval=-500, maxval=500)
out = ema(src, len)
plot(out, title="EMA", color=color.yellow, offset=offset, linewidth = 3)