// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © frazilex

//@version=4
study(title="Moving Average", shorttitle="MA", overlay=true, resolution="")
len = input(44, minval=1, title="Length")
src = input(close, title="Source")
offset = input(title="Offset", type=input.integer, defval=0, minval=-500, maxval=500)
out = sma(src, len)
plot(out, color=color.aqua, title="MA", offset=offset, linewidth = 3)